import express from "express";
import { testRoute } from "../api/auth/Test.js";
const router = express.Router();
import { resendOtp, signupRoute, verifyOtp } from "../api/auth/User.js";
import { createComment } from "../api/post/CreateComment.js";
import { createPost } from "../api/post/CreatePost.js";
import { deletePost } from "../api/post/DeletePost.js";
import { dislikeComment } from "../api/post/DislikeComment.js";
import { dislikePost } from "../api/post/DislikePost.js";
import { likeComment } from "../api/post/LikeComment.js";
import { likePost } from "../api/post/LikePost.js";

router.route("/test").post(testRoute);
router.route("/create").post(createPost);
router.route("/:id").delete(deletePost);
router.route("/post/like").post(likePost);
router.route("/post/dislike").post(dislikePost);
// router.route("/post/save").post(savePost);
router.route("/comment/create").post(createComment);
router.route("/comment/like").post(likeComment);
router.route("/comment/dislike").post(dislikeComment);
export default router;
